AppBundle\Entity\curso:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\cursoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: 255
        descripción:
            type: string
            length: 255
        precio:
            type: float
    lifecycleCallbacks: {  }
