AppBundle\Entity\HeskUsuariosEmails:
    type: entity
    table: hesk_usuarios_emails
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        usuario:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        idUsuario:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_usuario
    lifecycleCallbacks: {  }
