AppBundle\Entity\HeskStdReplies:
    type: entity
    table: hesk_std_replies
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 70
            options:
                fixed: false
                default: ''
        message:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        replyOrder:
            type: smallint
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: reply_order
        categories:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
