AppBundle\Entity\HeskRepliesArchivados:
    type: entity
    table: hesk_replies_archivados
    indexes:
        replyto:
            columns:
                - replyto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        replyto:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                default: ''
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        message:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        dt:
            type: datetime
            nullable: true
        attachments:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        respuestapccomponentes:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
                default: ''
            column: respuestaPccomponentes
        idusuario:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: idUsuario
        leidousuario:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: leidoUsuario
    lifecycleCallbacks: {  }
