AppBundle\Entity\HeskTicketsSoporte:
    type: entity
    table: hesk_tickets_soporte
    id:
        trackid:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        faq:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
