AppBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    id:
        dni:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        password:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
